"""Seed Payment Engine Fixtures into live PostgreSQL database."""
import asyncio
import uuid
from datetime import datetime, timezone

from app.services.supabase_client import get_supabase

async def seed():
    sb = get_supabase()
    school_id = "e1f11111-1111-1111-1111-111111111111" # Greenfield Public School

    # Check if records already exist
    existing = await sb.table("payment_orders").select("id").limit(1).aexecute()
    if existing.data and len(existing.data) > 0:
        print(f"Database already contains {len(existing.data)} payment records. Skipping seed.")
        return

    print("Seeding payment orders, attempts, and receipts...")

    transactions = [
        {
            "id": "c1000000-0000-0000-0000-000000000001",
            "transaction_id": "TXN202609030001",
            "ecosystem": "SCHOOL_FEE",
            "payment_type": "STUDENT_FEE",
            "payer_type": "STUDENT",
            "school_id": school_id,
            "amount": 25000.0,
            "currency": "INR",
            "purpose": "Tuition Fee",
            "payment_purpose": "Student Fee",
            "payment_method": "UPI PhonePe",
            "customer_name": "Rahul Sharma",
            "customer_email": "rahul.sharma@example.com",
            "customer_phone": "9876543210",
            "provider": "SBI_EPAY",
            "provider_order_id": "SBI-ORD-20260903-0001",
            "provider_payment_id": "SBI-PAY-9874102",
            "bank_ref_no": "UTR-SBI-9874102",
            "reference_number": "FEE-2026-000984",
            "status": "SUCCESS",
            "settlement_status": "SETTLED",
            "reconciliation_status": "MATCHED",
            "gross_amount": 25000.0,
            "net_settlement_amount": 25000.0,
            "refundable_amount": 25000.0,
            "total_refunded": 0.0,
            "created_at": "2026-09-03T20:58:00Z",
            "completed_at": "2026-09-03T20:58:12Z",
            "metadata": {"class": "Class 8-A", "academic_year": "2026-2027"}
        },
        {
            "id": "c1000000-0000-0000-0000-000000000002",
            "transaction_id": "TXN202609030002",
            "ecosystem": "SCHOOL_FEE",
            "payment_type": "STUDENT_FEE",
            "payer_type": "STUDENT",
            "school_id": school_id,
            "amount": 18500.0,
            "currency": "INR",
            "purpose": "Tuition Fee",
            "payment_purpose": "Student Fee",
            "payment_method": "UPI Google Pay",
            "customer_name": "Priya Verma",
            "customer_email": "priya.verma@example.com",
            "customer_phone": "9876543211",
            "provider": "ICICI_EAZYPAY",
            "provider_order_id": "ICICI-ORD-20260903-0002",
            "provider_payment_id": "ICICI-PAY-882910",
            "bank_ref_no": "UPI-ICICI-882910",
            "reference_number": "FEE-2026-000985",
            "status": "PENDING",
            "settlement_status": "PENDING",
            "reconciliation_status": "UNRECONCILED",
            "gross_amount": 18500.0,
            "net_settlement_amount": 18500.0,
            "refundable_amount": 18500.0,
            "total_refunded": 0.0,
            "created_at": "2026-09-03T20:57:00Z",
            "metadata": {"class": "Class 9-B", "academic_year": "2026-2027"}
        },
        {
            "id": "c1000000-0000-0000-0000-000000000003",
            "transaction_id": "TXN202609030003",
            "ecosystem": "SCHOOL_FEE",
            "payment_type": "STUDENT_FEE",
            "payer_type": "STUDENT",
            "school_id": school_id,
            "amount": 32000.0,
            "currency": "INR",
            "purpose": "Tuition Fee",
            "payment_purpose": "Student Fee",
            "payment_method": "UPI BHIM",
            "customer_name": "Amit Kumar",
            "customer_email": "amit.kumar@example.com",
            "customer_phone": "9876543212",
            "provider": "SBI_EPAY",
            "provider_order_id": "SBI-ORD-20260903-0003",
            "provider_payment_id": "SBI-PAY-9874103",
            "bank_ref_no": "UTR-SBI-9874103",
            "reference_number": "FEE-2026-000986",
            "status": "SUCCESS",
            "settlement_status": "SETTLED",
            "reconciliation_status": "MATCHED",
            "gross_amount": 32000.0,
            "net_settlement_amount": 32000.0,
            "refundable_amount": 32000.0,
            "total_refunded": 0.0,
            "created_at": "2026-09-03T20:56:00Z",
            "completed_at": "2026-09-03T20:56:15Z",
            "metadata": {"class": "Class 10-A", "academic_year": "2026-2027"}
        },
        {
            "id": "c1000000-0000-0000-0000-000000000004",
            "transaction_id": "TXN202609030004",
            "ecosystem": "SCHOOL_FEE",
            "payment_type": "STUDENT_FEE",
            "payer_type": "STUDENT",
            "school_id": school_id,
            "amount": 12000.0,
            "currency": "INR",
            "purpose": "Transport Fee",
            "payment_purpose": "Transport Fee",
            "payment_method": "UPI PhonePe",
            "customer_name": "Neha Singh",
            "customer_email": "neha.singh@example.com",
            "customer_phone": "9876543213",
            "provider": "HDFC_SMARTHUB",
            "provider_order_id": "HDFC-ORD-20260903-0004",
            "reference_number": "FEE-2026-000987",
            "status": "FAILED",
            "settlement_status": "FAILED",
            "reconciliation_status": "UNRECONCILED",
            "failure_code": "DECLINED_INSUFFICIENT_FUNDS",
            "failure_message": "Bank declined transaction: Insufficient balance",
            "gross_amount": 12000.0,
            "net_settlement_amount": 0.0,
            "refundable_amount": 0.0,
            "total_refunded": 0.0,
            "created_at": "2026-09-03T20:55:00Z",
            "completed_at": "2026-09-03T20:55:10Z",
            "metadata": {"class": "Class 8-B", "academic_year": "2026-2027"}
        },
        {
            "id": "c1000000-0000-0000-0000-000000000005",
            "transaction_id": "TXN202609030005",
            "ecosystem": "SCHOOL_FEE",
            "payment_type": "STUDENT_FEE",
            "payer_type": "STUDENT",
            "school_id": school_id,
            "amount": 9800.0,
            "currency": "INR",
            "purpose": "Activity & Lab Fee",
            "payment_purpose": "Student Fee",
            "payment_method": "UPI Google Pay",
            "customer_name": "Rohan Gupta",
            "customer_email": "rohan.gupta@example.com",
            "customer_phone": "9876543214",
            "provider": "ICICI_EAZYPAY",
            "provider_order_id": "ICICI-ORD-20260903-0005",
            "provider_payment_id": "ICICI-PAY-882911",
            "bank_ref_no": "UTR-ICICI-882911",
            "reference_number": "FEE-2026-000988",
            "status": "SUCCESS",
            "settlement_status": "SETTLED",
            "reconciliation_status": "MATCHED",
            "gross_amount": 9800.0,
            "net_settlement_amount": 9800.0,
            "refundable_amount": 9800.0,
            "total_refunded": 0.0,
            "created_at": "2026-09-03T20:54:00Z",
            "completed_at": "2026-09-03T20:54:14Z",
            "metadata": {"class": "Class 7-A", "academic_year": "2026-2027"}
        },
        {
            "id": "c1000000-0000-0000-0000-000000000006",
            "transaction_id": "TXN202609030006",
            "ecosystem": "SCHOOL_FEE",
            "payment_type": "STUDENT_FEE",
            "payer_type": "STUDENT",
            "school_id": school_id,
            "amount": 22400.0,
            "currency": "INR",
            "purpose": "Tuition Fee",
            "payment_purpose": "Student Fee",
            "payment_method": "UPI BHIM",
            "customer_name": "Kavya Patel",
            "customer_email": "kavya.patel@example.com",
            "customer_phone": "9876543215",
            "provider": "SBI_EPAY",
            "provider_order_id": "SBI-ORD-20260903-0006",
            "reference_number": "FEE-2026-000989",
            "status": "PENDING",
            "settlement_status": "PENDING",
            "reconciliation_status": "UNRECONCILED",
            "gross_amount": 22400.0,
            "net_settlement_amount": 22400.0,
            "refundable_amount": 22400.0,
            "total_refunded": 0.0,
            "created_at": "2026-09-03T20:52:00Z",
            "metadata": {"class": "Class 10-B", "academic_year": "2026-2027"}
        },
        {
            "id": "c1000000-0000-0000-0000-000000000007",
            "transaction_id": "TXN202609030007",
            "ecosystem": "SCHOOL_FEE",
            "payment_type": "STUDENT_FEE",
            "payer_type": "STUDENT",
            "school_id": school_id,
            "amount": 15000.0,
            "currency": "INR",
            "purpose": "Examination Fee",
            "payment_purpose": "Examination Fee",
            "payment_method": "UPI PhonePe",
            "customer_name": "Ishaan Verma",
            "customer_email": "ishaan.verma@example.com",
            "customer_phone": "9876543216",
            "provider": "HDFC_SMARTHUB",
            "provider_order_id": "HDFC-ORD-20260903-0007",
            "provider_payment_id": "HDFC-PAY-554109",
            "bank_ref_no": "UTR-HDFC-554109",
            "reference_number": "FEE-2026-000990",
            "status": "SUCCESS",
            "settlement_status": "SETTLED",
            "reconciliation_status": "MATCHED",
            "gross_amount": 15000.0,
            "net_settlement_amount": 15000.0,
            "refundable_amount": 15000.0,
            "total_refunded": 0.0,
            "created_at": "2026-09-03T20:50:00Z",
            "completed_at": "2026-09-03T20:50:18Z",
            "metadata": {"class": "Class 9-A", "academic_year": "2026-2027"}
        },
        {
            "id": "c1000000-0000-0000-0000-000000000008",
            "transaction_id": "TXN202609030008",
            "ecosystem": "SCHOOL_FEE",
            "payment_type": "STUDENT_FEE",
            "payer_type": "STUDENT",
            "school_id": school_id,
            "amount": 35450.0,
            "currency": "INR",
            "purpose": "Hostel Fee",
            "payment_purpose": "Hostel Fee",
            "payment_method": "UPI Google Pay",
            "customer_name": "Sunita Rao",
            "customer_email": "sunita.rao@example.com",
            "customer_phone": "9876543217",
            "provider": "ICICI_EAZYPAY",
            "provider_order_id": "ICICI-ORD-20260903-0008",
            "provider_payment_id": "ICICI-PAY-882912",
            "bank_ref_no": "UTR-ICICI-882912",
            "reference_number": "FEE-2026-000991",
            "status": "REFUNDED",
            "settlement_status": "SETTLED",
            "reconciliation_status": "MATCHED",
            "gross_amount": 35450.0,
            "net_settlement_amount": 0.0,
            "refundable_amount": 0.0,
            "total_refunded": 35450.0,
            "created_at": "2026-09-03T20:45:00Z",
            "completed_at": "2026-09-03T20:45:20Z",
            "metadata": {"class": "Class 6-B", "academic_year": "2026-2027"}
        },
        {
            "id": "c1000000-0000-0000-0000-000000000009",
            "transaction_id": "SUB-TXN-20260903-0009",
            "ecosystem": "SUBSCRIPTION",
            "payment_type": "SCHOOL_SUBSCRIPTION",
            "payer_type": "SCHOOL",
            "school_id": school_id,
            "amount": 49999.0,
            "currency": "INR",
            "purpose": "School ERP Subscription",
            "payment_purpose": "School ERP Subscription",
            "payment_method": "Net Banking",
            "customer_name": "Greenfield Public School Authority",
            "customer_email": "admin@greenfield.edu",
            "customer_phone": "9876543200",
            "provider": "SBI_EPAY",
            "provider_order_id": "SBI-SUB-20260903-0009",
            "provider_payment_id": "SBI-PAY-9874109",
            "bank_ref_no": "UTR-SBI-SUB-9874109",
            "reference_number": "SUB-2026-Q3",
            "status": "SUCCESS",
            "settlement_status": "SETTLED",
            "reconciliation_status": "MATCHED",
            "gross_amount": 49999.0,
            "net_settlement_amount": 49999.0,
            "refundable_amount": 49999.0,
            "total_refunded": 0.0,
            "created_at": "2026-09-03T20:30:00Z",
            "completed_at": "2026-09-03T20:30:35Z",
            "metadata": {"plan": "enterprise", "billing": "yearly"}
        }
    ]

    for item in transactions:
        try:
            ins = await sb.table("payment_orders").upsert(item).aexecute()
            order_id = item["id"]

            att_id = str(uuid.uuid4())
            await sb.table("payment_attempts").upsert({
                "id": att_id,
                "payment_order_id": order_id,
                "attempt_number": 1,
                "transaction_id": item["transaction_id"],
                "provider": item["provider"],
                "amount": item["amount"],
                "currency": item["currency"],
                "payment_method": item["payment_method"],
                "status": "SUCCESS" if item["status"] in ("SUCCESS", "REFUNDED") else item["status"],
                "provider_reference": item.get("provider_payment_id"),
                "gateway_response_code": "00" if item["status"] in ("SUCCESS", "REFUNDED") else "ERR_DECLINED",
                "gateway_response_message": "Approved" if item["status"] in ("SUCCESS", "REFUNDED") else item.get("failure_message", "Declined"),
                "created_at": item["created_at"],
                "completed_at": item.get("completed_at")
            }).aexecute()

            await sb.table("payment_orders").update({"current_attempt_id": att_id}).eq("id", order_id).aexecute()

            if item["status"] == "REFUNDED":
                await sb.table("payment_refunds").upsert({
                    "id": str(uuid.uuid4()),
                    "refund_reference": "REF-20260903-884102",
                    "payment_order_id": order_id,
                    "school_id": school_id,
                    "amount": item["amount"],
                    "reason": "Hostel booking cancelled by parent",
                    "status": "SUCCESS",
                    "provider_refund_id": "ICICI-REF-884102",
                    "created_at": "2026-09-03T21:15:00Z",
                    "completed_at": "2026-09-03T21:15:25Z"
                }).aexecute()

            if item["status"] == "SUCCESS":
                await sb.table("payment_receipts").upsert({
                    "id": str(uuid.uuid4()),
                    "receipt_number": f"RCP-202609-{item['transaction_id'][-6:]}",
                    "payment_order_id": order_id,
                    "school_id": school_id,
                    "school_name": "Greenfield Public School",
                    "customer_name": item["customer_name"],
                    "plan_name": item["purpose"],
                    "amount": item["amount"],
                    "currency": "INR",
                    "transaction_id": item["transaction_id"],
                    "payment_method": item["payment_method"],
                    "payment_date": item.get("completed_at", item["created_at"])
                }).aexecute()

        except Exception as e:
            print(f"Error inserting {item['transaction_id']}: {e}")

    print("Seeding completed successfully! 9 real multi-tenant transactions seeded.")

if __name__ == "__main__":
    asyncio.run(seed())
