import uuid
import mimetypes
from typing import Optional
import httpx
from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form
from fastapi.responses import StreamingResponse, RedirectResponse

from app.middleware.auth import get_current_user, require_school_id
from app.services.supabase_client import get_supabase
from app.config import settings

router = APIRouter()

ALLOWED_CATEGORIES = {
    "ai_generated",
    "my_uploads",
    "teacher_shared",
    "chat_shared",
    "school_notice",
}


# ── List documents ────────────────────────────────────────────────────────────

@router.get("")
async def list_documents(
    category: Optional[str] = None,
    limit: int = 50,
    offset: int = 0,
    user=Depends(get_current_user),
    school_id=Depends(require_school_id),
):
    """
    Return documents for the current user.
    Optionally filter by category.
    Includes documents shared WITH the user (teacher_shared, chat_shared, school_notice)
    as well as documents owned BY the user.
    """
    sb = get_supabase()

    query = (
        sb.table("user_documents")
        .select("*, shared_by:profiles!shared_by_id(full_name, avatar_url, role), owner:profiles!owner_id(full_name)")
        .eq("school_id", school_id)
        .or_(f"owner_id.eq.{user['id']},shared_with_id.eq.{user['id']}")
        .order("created_at", ascending=False)
        .limit(limit)
        .offset(offset)
    )

    if category and category in ALLOWED_CATEGORIES:
        query = query.eq("category", category)

    result = (await query.aexecute()).data or []

    # Build category counts in a second lightweight query (all docs, no pagination)
    counts_result = (
        await sb.table("user_documents")
        .select("category")
        .count("exact")
        .eq("school_id", school_id)
        .or_(f"owner_id.eq.{user['id']},shared_with_id.eq.{user['id']}")
        .aexecute()
    )

    # tally counts per category from the returned rows
    category_counts: dict[str, int] = {c: 0 for c in ALLOWED_CATEGORIES}
    for row in (counts_result.data or []):
        cat = row.get("category", "")
        if cat in category_counts:
            category_counts[cat] += 1

    return {
        "success": True,
        "school_id": school_id,
        "data": {
            "documents": result,
            "category_counts": category_counts,
        },
    }


# ── Save an AI-generated document ─────────────────────────────────────────────

@router.post("/save-ai")
async def save_ai_document(
    request: dict,
    user=Depends(get_current_user),
    school_id=Depends(require_school_id),
):
    """
    Save a text document generated by Shami AI directly to the Documents Hub.
    Automatically detects if a PDF/file was generated, uploads it to Supabase Storage,
    and registers it as a real file-backed document. Otherwise, saves it as text.
    """
    import re
    import urllib.parse
    import os

    title = request.get("title", "").strip()
    content = request.get("content", "").strip()
    session_id = request.get("session_id")
    description = request.get("description", "")

    if not title:
        raise HTTPException(status_code=400, detail="Title is required")
    if not content:
        raise HTTPException(status_code=400, detail="Content is required")

    sb = get_supabase()
    
    # Check if content contains a generated document download link
    match = re.search(r'/api/chat/download/([a-zA-Z0-9_\-\.\%]+)', content)
    
    file_uploaded = False
    record = {}

    if match:
        filename_raw = match.group(1)
        filename = urllib.parse.unquote(filename_raw)
        file_path = os.path.join(os.getcwd(), "assets", filename)
        
        if os.path.exists(file_path):
            try:
                # Read generated local file bytes
                with open(file_path, "rb") as f:
                    file_bytes = f.read()
                file_size = len(file_bytes)
                
                # Upload to Supabase Storage
                doc_id = str(uuid.uuid4())
                extension = filename.rsplit(".", 1)[-1].lower() if "." in filename else "bin"
                storage_path = f"documents/{school_id}/{user['id']}/{doc_id}.{extension}"
                
                supabase_url = settings.SUPABASE_URL.rstrip("/")
                storage_url = f"{supabase_url}/storage/v1/object/{storage_path}"
                mime = mimetypes.guess_type(filename)[0] or "application/octet-stream"
                
                headers = {
                    "apikey": settings.SUPABASE_SERVICE_ROLE_KEY,
                    "Authorization": f"Bearer {settings.SUPABASE_SERVICE_ROLE_KEY}",
                    "Content-Type": mime,
                    "x-upsert": "true",
                }
                
                async with httpx.AsyncClient(timeout=30.0) as client:
                    upload_response = await client.post(storage_url, headers=headers, content=file_bytes)
                
                if upload_response.status_code in (200, 201):
                    public_url_base = supabase_url.replace("http://kong:8000", "http://127.0.0.1:8000")
                    file_url = f"{public_url_base}/storage/v1/object/public/{storage_path}"
                    
                    record = {
                        "id": doc_id,
                        "school_id": school_id,
                        "owner_id": user["id"],
                        "title": title,
                        "description": description or f"Generated {extension.upper()} document from AI chat.",
                        "category": "ai_generated",
                        "file_url": file_url,
                        "file_name": filename,
                        "file_size": file_size,
                        "mime_type": mime,
                        "storage_path": storage_path,
                        "source_chat_session_id": session_id,
                    }
                    file_uploaded = True
            except Exception as e:
                print(f"Error transferring AI generated file to storage: {str(e)}")

    if not file_uploaded:
        # Fallback: Save as a text-only AI generated document (stored directly in DB)
        doc_id = str(uuid.uuid4())
        record = {
            "id": doc_id,
            "school_id": school_id,
            "owner_id": user["id"],
            "title": title,
            "description": description,
            "category": "ai_generated",
            "content": content,
            "source_chat_session_id": session_id,
            "mime_type": "text/plain",
        }

    result = (await sb.table("user_documents").insert(record).aexecute()).data

    return {"success": True, "data": {"document": result[0] if result else record}}


# ── Upload a personal document ─────────────────────────────────────────────────

@router.post("/upload")
async def upload_document(
    file: UploadFile = File(...),
    title: str = Form(""),
    description: str = Form(""),
    category: str = Form("my_uploads"),
    user=Depends(get_current_user),
    school_id=Depends(require_school_id),
):
    """
    Upload a personal document (PDF, DOCX, image, etc.) to Supabase Storage
    and register it in the user_documents table.
    """
    if category not in ALLOWED_CATEGORIES:
        category = "my_uploads"

    file_bytes = await file.read()
    file_size = len(file_bytes)

    # Limit to 20 MB
    if file_size > 20 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="File too large (max 20 MB)")
    if file_size == 0:
        raise HTTPException(status_code=400, detail="Empty file")

    safe_name = file.filename or "document"
    extension = safe_name.rsplit(".", 1)[-1].lower() if "." in safe_name else "bin"
    doc_id = str(uuid.uuid4())

    # Store in standard format under the documents bucket
    storage_path = f"documents/{school_id}/{user['id']}/{doc_id}.{extension}"
    supabase_url = settings.SUPABASE_URL.rstrip("/")
    storage_url = f"{supabase_url}/storage/v1/object/{storage_path}"
    headers = {
        "apikey": settings.SUPABASE_SERVICE_ROLE_KEY,
        "Authorization": f"Bearer {settings.SUPABASE_SERVICE_ROLE_KEY}",
        "Content-Type": file.content_type or "application/octet-stream",
        "x-upsert": "true",
    }

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            upload_response = await client.post(storage_url, headers=headers, content=file_bytes)
        
        if upload_response.status_code not in (200, 201):
            raise HTTPException(
                status_code=500,
                detail=f"Storage upload failed: {upload_response.text}"
            )
    except Exception as e:
        if isinstance(e, HTTPException):
            raise e
        raise HTTPException(status_code=500, detail=f"Storage upload request failed: {str(e)}")

    public_url_base = supabase_url.replace("http://kong:8000", "http://127.0.0.1:8000")
    file_url = f"{public_url_base}/storage/v1/object/public/{storage_path}"

    doc_title = title.strip() or safe_name
    mime = file.content_type or mimetypes.guess_type(safe_name)[0] or "application/octet-stream"

    sb = get_supabase()
    record = {
        "id": doc_id,
        "school_id": school_id,
        "owner_id": user["id"],
        "title": doc_title,
        "description": description,
        "category": category,
        "file_url": file_url,
        "file_name": safe_name,
        "file_size": file_size,
        "mime_type": mime,
        "storage_path": storage_path,
    }

    result = (await sb.table("user_documents").insert(record).aexecute()).data

    return {"success": True, "data": {"document": result[0] if result else record}}


# ── Delete a document ──────────────────────────────────────────────────────────

@router.delete("/{doc_id}")
async def delete_document(
    doc_id: str,
    user=Depends(get_current_user),
    school_id=Depends(require_school_id),
):
    """
    Delete a document. Only the document owner can delete it.
    Also removes the file from Supabase Storage if a storage_path exists.
    """
    sb = get_supabase()

    # Fetch the document to verify ownership
    doc_result = (
        await sb.table("user_documents")
        .select("*")
        .eq("id", doc_id)
        .eq("owner_id", user["id"])
        .eq("school_id", school_id)
        .maybe_single()
        .aexecute()
    ).data

    if not doc_result:
        raise HTTPException(status_code=404, detail="Document not found or access denied")

    # Remove file from storage if it exists
    storage_path = doc_result.get("storage_path")
    if storage_path:
        supabase_url = settings.SUPABASE_URL.rstrip("/")
        # Extract the prefix path inside the documents bucket
        if storage_path.startswith("documents/"):
            prefix = storage_path[len("documents/"):]
        else:
            prefix = storage_path

        delete_url = f"{supabase_url}/storage/v1/object/documents"
        headers = {
            "apikey": settings.SUPABASE_SERVICE_ROLE_KEY,
            "Authorization": f"Bearer {settings.SUPABASE_SERVICE_ROLE_KEY}",
            "Content-Type": "application/json",
        }
        
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                delete_response = await client.request(
                    "DELETE",
                    delete_url,
                    headers=headers,
                    json={"prefixes": [prefix]}
                )
            if delete_response.status_code not in (200, 201, 204):
                print(f"Failed to delete storage object: {delete_response.text}")
        except Exception as e:
            print(f"Error during storage object deletion: {str(e)}")

    await sb.table("user_documents").delete().eq("id", doc_id).aexecute()

    return {"success": True, "message": "Document deleted"}


# ── Download / get document content ───────────────────────────────────────────

@router.get("/{doc_id}/download")
async def download_document(
    doc_id: str,
    user=Depends(get_current_user),
    school_id=Depends(require_school_id),
):
    """
    Return document content.
    - For file documents: redirect to the Supabase public URL.
    - For AI-generated text documents: return content as plain text download.
    """
    sb = get_supabase()

    doc = (
        await sb.table("user_documents")
        .select("*")
        .eq("id", doc_id)
        .eq("school_id", school_id)
        .or_(f"owner_id.eq.{user['id']},shared_with_id.eq.{user['id']}")
        .maybe_single()
        .aexecute()
    ).data

    if not doc:
        raise HTTPException(status_code=404, detail="Document not found or access denied")

    if doc.get("file_url"):
        # Redirect to the Supabase public URL
        return RedirectResponse(url=doc["file_url"])

    # AI-generated text document — stream as a .txt file
    content = doc.get("content", "")
    filename = f"{doc.get('title', 'document')}.txt"
    filename_safe = filename.replace('"', "'")

    return StreamingResponse(
        iter([content.encode("utf-8")]),
        media_type="text/plain; charset=utf-8",
        headers={
            "Content-Disposition": f'attachment; filename="{filename_safe}"',
        },
    )
