FROM livekit/egress:v1.8.4

USER root

# Install Python 3 for health check web server
RUN apt-get update && apt-get install -y --no-install-recommends python3 && rm -rf /var/lib/apt/lists/*

COPY entrypoint_egress.sh /entrypoint.sh
COPY health.py /health.py
COPY policy.json /etc/opt/chrome/policies/managed/policy.json

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
